# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-27 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MTOAPP', '0004_auto_20190127_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MTOAPP.Student'),
        ),
    ]
